name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"

      - name: Get Tag
        id: tag
        run: |
          latest_tag=$(curl -sSL --retry 5 "https://api.github.com/repos/v2fly/v2ray-core/releases/latest" | jq .tag_name | awk -F '"' '{print $2}')
          if [[ -z "${{ github.event.inputs.tag }}" ]]; then
            echo "Use the latest release tag of wcfhttp: ${latest_tag}"
            echo "tag=${latest_tag}" >> $GITHUB_OUTPUT
          else
            echo "Use tag: ${{ github.event.inputs.tag }}"
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Windows executable
        run: pyinstaller wcfhttp.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/wcfhttp.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tag.outputs.tag }}
          files: |
            dist/wcfhttp.exe     
