name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Build Windows executable
        run: pyinstaller wcfhttp.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/wcfhttp.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/wcfhttp.exe     
