name: Build wcfhttp

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"

      - name: Get Tag
        id: tag
        run: |
          echo "Use tag: ${{ github.event.inputs.tag }}"
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build wcfhttp
        run: pyinstaller wcfhttp.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/wcfhttp.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tag.outputs.tag }}
          files: |
            dist/wcfhttp.exe    
          tag_name: ${{ steps.tag.outputs.tag }}

 
